<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('admin_settings')->insert([
            [
                'id' => 1,
                'title' => 'Odeka',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut tortor rutrum massa efficitur tincidunt vel nec lacus. Curabitur porta aliquet diam, eu gravida neque lacinia.',
                'keywords' => 'donations,support,creators,Creaty,subscription',
                'update_length' => 700,
                'status_page' => '1',
                'email_verification' => '',
                'email_no_reply' => 'noreply@odeka.org',
                'email_admin' => 'admin@odeka.org',
                'captcha' => 'off',
                'file_size_allowed' => 3072000,
                'google_analytics' => '<!-- Google tag (gtag.js) -->\r\n<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-X8XEM7KGQG\"></script>\r\n<script>\r\n  window.dataLayer = window.dataLayer || [];\r\n  function gtag(){dataLayer.push(arguments);}\r\n  gtag(\'js\', new Date());\r\n\r\n  gtag(\'config\', \'G-X8XEM7KGQG\');\r\n</script>',
                'paypal_account' => 'paypal@yousite.com',
                'twitter' => '',
                'facebook' => 'https://www.facebook.com/profile.php?id=100088898272813&mibextid=LQQJ4d',
                'pinterest' => '',
                'instagram' => 'https://instagram.com/odekamedia?utm_source=qr%0A',
                'google_adsense' => '',
                'currency_symbol' => 'FCFA',
                'currency_code' => 'XOF',
                'min_subscription_amount' => 200,
                'payment_gateway' => 'PayPal',
                'min_width_height_image' => '400',
                'fee_commission' => 20,
                'max_subscription_amount' => 10000,
                'date_format' => 'd M, Y',
                'link_privacy' => 'https://odeka.org/p/privacy',
                'link_terms' => 'https://odeka.org/p/terms-of-service',
                'currency_position' => 'right_space',
                'facebook_login' => 'off',
                'amount_min_withdrawal' => 500,
                'youtube' => '',
                'github' => '',
                'comment_length' => 400,
                'days_process_withdrawals' => 2,
                'google_login' => 'off',
                'number_posts_show' => 5,
                'number_comments_show' => 5,
                'registration_active' => '1',
                'account_verification' => '1',
                'logo' => 'logo-1745824531.png',
                'logo_2' => 'logo_2-1745824531.png',
                'favicon' => 'favicon-1747612870.png',
                'home_index' => 'home_index.png',
                'bg_gradient' => 'bg-gradient.jpg',
                'img_1' => 'img_1.svg',
                'img_2' => 'img_2.svg',
                'img_3' => 'img_3.svg',
                'img_4' => 'img_4.png',
                'avatar' => 'default-1753321771.png',
                'show_counter' => 'off',
                'color_default' => '#1481ba',
                'decimal_format' => 'comma',
                'version' => '5.9',
                'link_cookies' => 'https://odeka.org/p/cookies',
                'story_length' => 500,
                'maintenance_mode' => 'off',
                'company' => 'Odeka Media',
                'country' => 'Togo',
                'address' => '',
                'city' => 'Lomé',
                'zip' => '',
                'vat' => '',
                'widget_creators_featured' => 'on',
                'home_style' => 0,
                'file_size_allowed_verify_account' => 5120,
                'payout_method_paypal' => 'on',
                'payout_method_bank' => 'off',
                'min_tip_amount' => 500,
                'max_tip_amount' => 100000,
                'min_ppv_amount' => 500,
                'max_ppv_amount' => 100000,
                'min_deposits_amount' => 500,
                'max_deposits_amount' => 100000,
                'button_style' => 'rounded',
                'twitter_login' => 'off',
                'hide_admin_profile' => 'off',
                'requests_verify_account' => 'on',
                'navbar_background_color' => '#ffffff',
                'navbar_text_color' => '#3a3a3a',
                'footer_background_color' => '#ffffff',
                'footer_text_color' => '#5f5f5f',
                'preloading' => 'off',
                'preloading_image' => '',
                'watermark' => 'on',
                'earnings_simulator' => 'on',
                'custom_css' => '',
                'custom_js' => '',
                'alert_adult' => 'off',
                'genders' => 'male,female',
                'cover_default' => '',
                'who_can_see_content' => 'all',
                'users_can_edit_post' => 'on',
                'disable_wallet' => 'off',
                'disable_banner_cookies' => 'on',
                'wallet_format' => 'real_money',
                'maximum_files_post' => 5,
                'maximum_files_msg' => 5,
                'announcement' => 'Bienvenue sur la V2 d\'Odeka ! 🎉\r\n\r\nFélicitations, vous êtes désormais créateur de contenu. Exprimez votre créativité, engagez votre audience, et profitez de nouvelles opportunités.\r\n\r\nL\'aventure commence maintenant. Bonne création !\r\n\r\nL\'équipe Odeka',
                'announcement_show' => 'creators',
                'announcement_cookie' => 'h5ELqkYqcqSyeDlimstV',
                'limit_categories' => 3,
                'captcha_contact' => 'on',
                'disable_tips' => 'off',
                'payout_method_payoneer' => 'off',
                'payout_method_zelle' => 'off',
                'type_announcement' => 'danger',
                'referral_system' => 'on',
                'auto_approve_post' => 'on',
                'watermark_on_videos' => 'on',
                'percentage_referred' => 15,
                'referral_transaction_limit' => 10,
                'video_encoding' => 'off',
                'live_streaming_status' => 'on',
                'live_streaming_minimum_price' => 500,
                'live_streaming_max_price' => 50000,
                'agora_app_id' => 'b85f9bbd570f4641bd5bdf6042605146',
                'tiktok' => 'https://www.tiktok.com/@odekamedia?_t=8jrq0lYpMKk&_r=1',
                'snapchat' => 'https://t.snapchat.com/wDtLuE0D',
                'limit_live_streaming_paid' => 120,
                'limit_live_streaming_free' => 0,
                'live_streaming_free' => '1',
                'type_withdrawals' => 'custom',
                'shop' => 1,
                'min_price_product' => 500,
                'max_price_product' => 100000,
                'digital_product_sale' => 1,
                'custom_content' => 1,
                'tax_on_wallet' => 1,
                'stripe_connect' => 0,
                'stripe_connect_countries' => '',
                'physical_products' => 1,
                'disable_login_register_email' => 0,
                'disable_contact' => 0,
                'specific_day_payment_withdrawals' => 0,
                'disable_new_post_notification' => 0,
                'disable_search_creators' => 0,
                'search_creators_genders' => 0,
                'generate_qr_code' => 0,
                'autofollow_admin' => 1,
                'allow_zip_files' => 0,
                'reddit' => '',
                'telegram' => '',
                'linkedin' => '',
                'push_notification_status' => 0,
                'onesignal_appid' => '',
                'onesignal_restapi' => '',
                'status_pwa' => 0,
                'zip_verification_creator' => 0,
                'amount_max_withdrawal' => 50000,
                'story_status' => 1,
                'story_image' => 1,
                'story_text' => 1,
                'story_max_videos_length' => 30,
                'payout_method_western_union' => 'on',
                'payout_method_crypto' => 'off',
                'threads' => '',
                'watermak_video' => 'watermak_video-1745824531.png',
                'coconut_key' => '',
                'encoding_method' => 'ffmpeg',
                'allow_scheduled_posts' => 1,
                'google_tag_manager_head' => '<!-- Google Tag Manager -->\r\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\r\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\r\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\r\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\r\n})(window,document,\'script\',\'dataLayer\',\'GTM-M92DPR5K\');</script>\r\n<!-- End Google Tag Manager -->',
                'google_tag_manager_body' => '<!-- Google Tag Manager (noscript) -->\r\n<noscript><iframe src=\"https://www.googletagmanager.com/ns.html?id=GTM-M92DPR5K\"\r\nheight=\"0\" width=\"0\" style=\"display:none;visibility:hidden\"></iframe></noscript>\r\n<!-- End Google Tag Manager (noscript) -->',
                'live_streaming_private' => '',
                'live_streaming_minimum_price_private' => 0.00,
                'live_streaming_max_price_private' => 0.00,
                'limit_live_streaming_private' => 10,
                'show_address_company_footer' => 1,
                'watermark_position' => 'center',
                'coconut_region' => 'Virginia',
                'payout_method_mercadopago' => 'off',
                'theme' => 'dark',
                'allow_creators_deactivate_profile' => 0,
                'allow_epub_files' => 0,
                'gifts' => 1,
                'disable_free_post' => 0,
                'disable_explore_section' => 0,
                'disable_creators_section' => 0,
                'phone' => '+228 70 31 93 59',
                'allow_free_items_shop' => 0,
                'allow_external_links_shop' => 1,
                'users_can_delete_messages' => 1,
                'delete_old_users_inactive' => 0,
            ]
        ]);
    }
}
